services:
  - type: web
    name: airchitect-oil-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: standard
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
